title: Frontend Indo
email: frontendindo@gmail.com
description: >-
  Frontend Indonesia
baseurl: ""
url: "http://frontendindo.github.io/"
twitter_username: frontendindo
github_username:  frontendindo
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
